# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Page Title')),
                ('body', models.TextField(max_length=5000, verbose_name='Body')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Section Title')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Section'),
        ),
    ]
