# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Page Title')),
                ('body', models.CharField(max_length=5000, verbose_name='Body')),
                ('pub_date', models.DateField(verbose_name='Date Published')),
            ],
        ),
    ]
