# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(max_length=5000, verbose_name='Body'),
        ),
    ]
