# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160130_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='page_text',
        ),
    ]
