# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160214_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='none.jpg', upload_to='media/'),
        ),
    ]
