# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160130_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_text',
            new_name='title',
        ),
    ]
