# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default='none.jpg', upload_to='page/media/'),
        ),
    ]
