# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('name', models.CharField(max_length=100, verbose_name='Full Names')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(max_length=5000, verbose_name='Body')),
                ('cc_myself', models.BooleanField(default=False, verbose_name='CC Sender')),
            ],
        ),
    ]
