# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0002_sitedetails_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetails',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
