# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0003_auto_20160131_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteDetails',
            new_name='SiteDetail',
        ),
    ]
