# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0004_auto_20160131_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='key',
            field=models.CharField(default=datetime.datetime(2016, 1, 31, 6, 56, 57, 681133, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
